fix & feat : mostly some refactoring work + responsiveness
palestirnative/palestirnative pull request #66
Opened 2024-03-08 11:30 UTC by shiraz27

## Description

2024-03-08 18:24 UTC, daliovic requested changes
Great job! Just some minor Tailwind improvements and we're good to go

2024-03-08 18:24 UTC, daliovic commented on islands/navigation.tsx
> +  };
It's better to use `end` and `start` when dealing with positionning, padding, margin etc 
```suggestion
  const getIconClass = () => {
    return `absolute inset-y-0 end-0 flex items-center pe-3`
  };
```

https://tailwindcss.com/docs/top-right-bottom-left

2024-03-08 18:24 UTC, daliovic commented on islands/form/tag-input.tsx
> +  };
It's better to use logical properties when dealing with positioning, padding, margin etc

```suggestion
  const getImageClass = () => {
    return "h-5 w-5 rounded-full ms-4 object-contain";
  };
```
https://tailwindcss.com/docs/margin#using-logical-properties

2024-03-09 10:27 UTC, shiraz27 commented
@daliovic Amazing comments! thnk you for referencing the docs, I also thought the code would get extremely bloated with these direction logic functions, this is definitely more sustainable.

2024-03-09 10:29 UTC, daliovic approved these changes
Amazing!

2024-03-09 10:32 UTC, merged